name: CMake Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 480
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            suffix: so
          - os: macos-latest
            suffix: dylib

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install pkg-config
            sudo apt-get install librdkafka-dev
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            brew install pkg-config
            brew install librdkafka
          fi

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Prepare for release
        run: |
          cp build/libMetricProducer.${{ matrix.suffix }} libMetricProducer.${{ matrix.suffix }}

      - name: Upload Artifact Shared
        uses: actions/upload-artifact@v2
        with:
          name: library-${{ matrix.os }}-${{ matrix.suffix }}
          path: ./libMetricProducer.${{ matrix.suffix }}
