name: CMake Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 480
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            suffix: so
          - os: macos-latest
            suffix: dylib

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install pkg-config
            sudo apt-get install librdkafka-dev
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            brew install pkg-config
            brew install librdkafka
          fi

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Prepare for release
        run: |
          cp build/libMetricProducer.${{ matrix.suffix }} libMetricProducer.${{ matrix.suffix }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Library to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./libMetricProducer.${{ matrix.suffix }}
          asset_name: libMetricProducer.${{ matrix.suffix }}
          asset_content_type: application/octet-stream
